repos:
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8

  - repo: local
    hooks:
      - id: validate-repo
        name: validate-repo
        entry: python scripts/validate_repo.py
        language: system
        pass_filenames: false

